name: release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        required: true
        options:
          - prerelease
          - release
      version-type:
        type: choice
        required: true
        options:
          - patch
          - minor
          - major
      prerelease-type:
        type: choice
        required: true
        options:
          - rc
          - beta
          - alpha
      dry-run:
        type: choice
        default: ""
        options:
          - -d
          - ""

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - run: bun i --frozen-lockfile
      - run: bun i -g npm@latest
      - if: inputs.mode == 'prerelease'
        run: npm run pre-release -- -i ${{ inputs.version-type }} --preRelease=${{ inputs.prerelease-type }} ${{inputs.dry-run}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: inputs.mode == 'release'
        run: npm run release -- -i ${{ inputs.version-type }} ${{inputs.dry-run}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
